### ISSUE TITLE
ORD Metadata changes

### ISSUE THREAD

**Issue by RamIndia** [cap-js/ord#38]
Please find attached the ord documents we walked through in our review: 
- Reference CAP application: https://github.com/SAP-samples/cloud-cap-samples/tree/main/bookstore
- [1.ord.json](https://github.com/user-attachments/files/16372814/1.ord.json) is the one generated today by cds compile index.cds --to ord in cap/samples/bookstore
- [2.ord.json](https://github.com/user-attachments/files/16372820/2.ord.json) is the same with corrections 
- → compare both in VSCode, e.g. with code --diff 1.ord.json 2.ord.json

Here are the changes decided for the ORD document : 

- [x] Don’t add a suffix if I already specified a **.json** suffix in the **-o / —dest** parameter
- [x] Use **.ord.json** as file suffix instead of .ord if not 
- [x] Always add  ```"$schema": "https://sap.github.io/open-resource-discovery/spec-v1/interfaces/Document.schema.json"```
- [x] Never use CSN's **.namespace** property but always just use the fully-qualified names from **.definitions** 
- [x] ORD namespace (used as prefix in several ORD IDs) = `package.name.replace(/@/,'').replace(/\//g,’')`, unless explicitly configured in cds.env.ord.namespace

**products** 

- [x] `"ordId": "customer:product:capire.bookstore:”`→ i.e. package.name.replace(/@/,'').replace(/\//g,'.')
- [x] `"vendor": "customer:vendor:customer:” `
- [x] `"title": “capire bookstore”`→ i.e. package.name.replace(/@/,'').replace(/\//g,'.')
- [x] `"shortDescription": “capire bookstore"` → i.e. package.name.replace(/@/,'').replace(/\//g,' ')

**groups** 

- [x] `"title": "Catalog Service”` → i.e. without appending “ Title”
- [x] The groups for events shall be services, not the individual events → but then the last two entries in the bookstore sample are duplicates

**packages**

- [x] → the namespace was wrong and the package name shall be `package.name.replace(/@/,'').replace(/\//g,'.')`
- [x] `"partOfProducts": [ "customer:product:capire.bookstore:” ]` → has to be the same as the product name in the products section
- [x] `"vendor": "customer:vendor:customer:”` → has to be the same as the vendor in the products section
- [x] `"title": "capire bookshop”` → take what is there, don’t add extra text like “sample title for"
- [x] `“shortDescription"` → take what is there, don’t add extra text like “Here’s the short description for ..."
- [x] `“description"` → take what is there, don’t add extra text like “Here’s the short description for ..."

**consumptionBundles**
- [x] skip (do not include)

**apiResources**

- [x] `"title": "Catalog Service”` → take what is there, don’t add extra text like “The service is for ..."
- [x] `“shortDescription": "Catalog Service” `→ take what is there, don’t add extra text like “Here we have the shortDescription for ..."
- [x] `“description": "Catalog Service”` → take what is there, don’t add extra text like “Here we have the description for ..."
- [x] `"partOfPackage": "customer.capirebookstore:package:capire.bookshop:v1” `→ correct namespace prefix in package ref - use appName as packageName as a fallback

**eventResources**

- [x] The entries are service-level, not event-level
- [x] IMPORTANT: test with more than one event declared per service → should end up in one entry, not many

Explanation:
- one catalog contains several events -> one event resource in ORD

**Tests**
- [x] Jest tests and CI/CD

**Comment by aramovic79** [comment]
TODO: Check-mark the check-boxes given in the issue body **(only) after merging** the related pull requests. 

cc: @ductaily @Fannon @RoshniNaveenaS

**Comment by aramovic79** [comment]
Regarding  the ```Don’t add a suffix if I already specified a .json suffix in the -o / —dest parameter```:
The fix should be implemented in the [cds-dk](https://github.tools.sap/cap/cds-dk/blob/1095e2fae2037d174a9968c76629b92a84586337/bin/compile/index.js#L251) repo, not in the ord plugin.
Compiler is always attaching the suffix that is equal to the ```-to``` parameter value.
Check by running e.g. : ```cds compile srv/services.cds -2 csn -o ORD15.someext``` => Result is: ```ORD15.someext.csn ```(or -2 SQL)

@RoshniNaveenaS @ductaily @Fannon

**Comment by aramovic79** [comment]
The same as above stands for ```Use .ord.json as file suffix instead of .ord if not```. 
Checkmarking both issues because the fix shall not be done in cap-js/ord plugin.

@RoshniNaveenaS @ductaily @Fannon

**Comment by RamIndia** [comment]
> Regarding the `Don’t add a suffix if I already specified a .json suffix in the -o / —dest parameter`: The fix should be implemented in the [cds-dk](https://github.tools.sap/cap/cds-dk/blob/1095e2fae2037d174a9968c76629b92a84586337/bin/compile/index.js#L251) repo, not in the ord plugin. Compiler is always attaching the suffix that is equal to the `-to` parameter value. Check by running e.g. : `cds compile srv/services.cds -2 csn -o ORD15.someext` => Result is: `ORD15.someext.csn `(or -2 SQL)
> 
> @RoshniNaveenaS @ductaily @Fannon

@stewsk: As of now cds compile -2 always appends the extension, can we ignore appending the format if extension is specified in the -o parameter?

**Comment by ductaily** [comment]
@aramovic79 @Fannon

The issue regarding `Don’t add a suffix if I already specified a .json suffix in the -o / —dest parameter` will be resolved in cds-dk 8.2.0. See corresponding issue: https://github.tools.sap/cap/issues/issues/16685

**Comment by aramovic79** [comment]
@zongqichen @ductaily : I've checked marked items that are done. I'm not sure for the remaining. Could you please take a look and check-mark the finished ones? Thanks!

**Comment by zongqichen** [comment]
Hi @aramovic79, I marked the Jest and CICD pipeline item. I think we basically introduced the test and action as pipeline.

**Comment by aramovic79** [comment]
All the tasks in this issue are addressed, hence closing this issue.

@RamIndia @RoshniNaveenaS @zongqichen @Fannon : Are you fine with this?
