### ISSUE TITLE
Allow generic override / expand of ORD information on global level

### ISSUE THREAD

**Issue by Fannon** [cap-js/ord#49]
Right now, the documentation in https://github.com/cap-js/ord/blob/main/ord.md indicates two ways to add ORD information: 

* Add global ord config, that is then applied to several places
* Override ORD information via Annotations on CDS Models like a Service. 

This still misses some flexibility:
* It's not possible to add new ORD resources or resource types that are not supported / provided by the CAP Framework right now (e.g. Data Products or Entity Types)
* It's not possible to override something in case this is necessary

### Suggestion

Add a completely generic way to provide partial ORD documents, e.g. like:

```js
// cdsrc.json or package.json cds context
  "ord": {
    "namespace": "sap.sample",
    "description": "this is my custom description",
    "policyLevel": "sap:core:v1",
    "customOrd": "./ord/custom.ord.json" // Link to static ORD JSON file to merge in
  }
```

Expected behavior: 
* The interface of the `custom` object is the same as the ORD Document interface. 
* The collections (like "dataProducts" are iterated and for those resource types that CAP supports we check if they are already defined through CAP. If yes, the custom definition wins (override)"
* All content in the `custom` object are merged to the final ORD Document that the CAP plugin produces.

**Comment by zongqichen** [comment]
Hi @Fannon, it's a good proposal. I would suggest that renames *customOrd* -> *customOrdContentFile*, with more context.

**Comment by Fannon** [comment]
> Hi @Fannon, it's a good proposal. I would suggest that renames _customOrd_ -> _customOrdContentFile_, with more context.

Sounds good!

**Comment by zongqichen** [comment]
Use cases:
1. We want to add new ord resources that are not supported by cap framework, e.g. dataProducts
2. We need to enhance the list of generated ord resources, e.g. adding new pacakge or new apiResource
3. We need to patch the existing generated ord resources, e.g. customized the existing package
- override property(string, array, object) generated by the plugin
- add new property(string, array, object)
- delete property when it set to null (still be open how to cover it properly)

4. Not in scope:
- delete pre-genereated ord top level resources: e.g. packages, apiResources

**Comment by Fannon** [comment]
We should completely follow the way how the upcoming ORD Diff documents work. See  https://github.tools.sap/CentralEngineering/open-resource-discovery-specification/pull/862/files

```md
ORD Delta Documents
ORD Delta Documents are an optional feature that allows to efficiently describe a "patch" / "diff" to the static baseline state.

This applies to dynamic metadata, which may differ per tenant and / or change at run-time.

Fully redescribing a resource, even though maybe only one or two attributes of it have effectively changed cause efficiency issues. To address this, the ORD Document Delta format MAY be used, IF the connected ORD Aggregators support it.

The ORD Document Delta format is identical to the regular ORD Document format, with the following exceptions:

On document root level, "delta": true MUST be set. As file extension, we RECOMMEND .delta.json.
It only describes the resources and attributes that need to be added, changed or deleted.
All attributes are optional, except for the primary ID of the described resource (usually [ORD ID](https://file+.vscode-resource.vscode-cdn.net/c%3A/SAPDevelop/open-resource-discovery-specification/docs/spec-v1/index.md#ord-id))
Attributes MAY be set to null, which has the semantic that the attribute should be removed when merging (similar to [RFC 7386](https://www.rfc-editor.org/rfc/rfc7386)).
Arrays are fully overwritten, with the notable exception of the root level arrays that constitute the collections of ORD resources / taxonomy.
To delete an existing ORD resource / taxonomy, add its ORD ID to the array and add a "$delete": true marker
If the resource definition(s) changed, the version SHOULD and the lastUpdate MUST be updated. This will trigger a re-fetch of the attached definition files.
The format MUST only be used to describe dynamic-perspective differences compared to a fully described static perspective.
MUST set "perspective": "system-instance"
SHOULD define "describedSystemVersion": { "version": "???" }, as the system version is where the merge between the static perspective and the delta-dynamic perspective happens.
```

**Comment by zongqichen** [comment]
> Regarding top-level properties that are not collections / arrays: Ignore them for now or just overwrite them?
> 
> Tendency: Just overwrite top-level properties that are not arrays, or unset them (null). Don't do this recursively. The recursive JSON Merge patch is only done inside of the array items

I would like ignore top-level properties that are string in customOrdFile. Print log error to reflect it. The benefit is that we can avoid the situation when same property defined in .cdsrc.json and customOrdFile with different value.
